// <auto-generated />
using System;
using DigitalTwin.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DigitalTwin.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DigitalTwinDbContext))]
    [Migration("20260323202239_AddSchedulerExplainabilityAndControl")]
    partial class AddSchedulerExplainabilityAndControl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DigitalTwin.Domain.Entities.Printer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsAmsSupported")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastBindSyncAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal?>("NozzleDiameterMm")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("PrintStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Structure")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("printers", (string)null);
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.PrinterAmsUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AmsDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("AmsIndex")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool?>("ForceUpdate")
                        .HasColumnType("boolean");

                    b.Property<int?>("HumidityLevel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LatestVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PrinterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReleaseStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("TemperatureCelsius")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId", "AmsIndex")
                        .IsUnique();

                    b.ToTable("printer_ams_units", (string)null);
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.PrinterFirmwareStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool?>("ForceUpdate")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastVersionSyncAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LatestVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PrinterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReleaseStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId")
                        .IsUnique();

                    b.ToTable("printer_firmware_statuses", (string)null);
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.PrinterMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("CreateTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DesignId")
                        .HasColumnType("integer");

                    b.Property<string>("DesignTitle")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Detail")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("ExternalMessageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ExternalTaskId")
                        .HasColumnType("bigint");

                    b.Property<int?>("IsRead")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PrinterId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RelatedPrinterTaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SourceUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TaskStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ExternalMessageId")
                        .IsUnique();

                    b.HasIndex("ExternalTaskId");

                    b.HasIndex("PrinterId");

                    b.HasIndex("RelatedPrinterTaskId");

                    b.ToTable("printer_messages", (string)null);
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.PrinterSimulationControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivePrinterTaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PrinterId")
                        .HasColumnType("uuid");

                    b.Property<string>("SimulationState")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsLocked");

                    b.HasIndex("LockedUntilUtc");

                    b.HasIndex("PrinterId")
                        .IsUnique();

                    b.ToTable("printer_simulation_controls", (string)null);
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.PrinterTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BedType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("CostTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DesignTitle")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("DesignTitleTranslated")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DeviceModel")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("EndTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExternalTaskId")
                        .HasColumnType("bigint");

                    b.Property<int?>("FailedType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSimulated")
                        .HasColumnType("boolean");

                    b.Property<int?>("LengthMm")
                        .HasColumnType("integer");

                    b.Property<string>("Mode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("PrinterId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SimulatedCompleteAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("SourceUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusText")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("WeightGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ExternalTaskId")
                        .IsUnique();

                    b.HasIndex("PrinterId");

                    b.ToTable("printer_tasks", (string)null);
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.PrinterTaskAmsDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Ams")
                        .HasColumnType("integer");

                    b.Property<int?>("AmsId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilamentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FilamentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("NozzleId")
                        .HasColumnType("integer");

                    b.Property<Guid>("PrinterTaskId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SlotId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceColor")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TargetColor")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TargetFilamentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("WeightGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("PrinterTaskId", "Ams", "AmsId", "SlotId", "NozzleId");

                    b.ToTable("printer_task_ams_details", (string)null);
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.ScheduledPrintJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowAnyPrinter")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("AssignedPrinterId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompatibilityNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("DueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EstimatedDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<decimal?>("EstimatedFilamentGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset?>("EstimatedFinishAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EstimatedStartAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsSimulatedInput")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("PreferredPrinterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedColor")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RequestedMaterialType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("RequestedStartAfterUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SchedulerDecisionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("StartedPrinterTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedPrinterId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("DueAtUtc");

                    b.HasIndex("PreferredPrinterId");

                    b.HasIndex("Priority");

                    b.HasIndex("RequestedStartAfterUtc");

                    b.HasIndex("StartedPrinterTaskId");

                    b.HasIndex("Status");

                    b.ToTable("scheduled_print_jobs", (string)null);
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.SchedulerControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean");

                    b.Property<string>("PauseReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("scheduler_controls", (string)null);
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.PrinterAmsUnit", b =>
                {
                    b.HasOne("DigitalTwin.Domain.Entities.Printer", "Printer")
                        .WithMany("AmsUnits")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.PrinterFirmwareStatus", b =>
                {
                    b.HasOne("DigitalTwin.Domain.Entities.Printer", "Printer")
                        .WithOne("FirmwareStatus")
                        .HasForeignKey("DigitalTwin.Domain.Entities.PrinterFirmwareStatus", "PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.PrinterMessage", b =>
                {
                    b.HasOne("DigitalTwin.Domain.Entities.Printer", "Printer")
                        .WithMany()
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DigitalTwin.Domain.Entities.PrinterTask", "RelatedPrinterTask")
                        .WithMany()
                        .HasForeignKey("RelatedPrinterTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Printer");

                    b.Navigation("RelatedPrinterTask");
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.PrinterSimulationControl", b =>
                {
                    b.HasOne("DigitalTwin.Domain.Entities.Printer", "Printer")
                        .WithOne("SimulationControl")
                        .HasForeignKey("DigitalTwin.Domain.Entities.PrinterSimulationControl", "PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.PrinterTask", b =>
                {
                    b.HasOne("DigitalTwin.Domain.Entities.Printer", "Printer")
                        .WithMany()
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.PrinterTaskAmsDetail", b =>
                {
                    b.HasOne("DigitalTwin.Domain.Entities.PrinterTask", "PrinterTask")
                        .WithMany("AmsDetails")
                        .HasForeignKey("PrinterTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrinterTask");
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.ScheduledPrintJob", b =>
                {
                    b.HasOne("DigitalTwin.Domain.Entities.Printer", "AssignedPrinter")
                        .WithMany()
                        .HasForeignKey("AssignedPrinterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DigitalTwin.Domain.Entities.Printer", "PreferredPrinter")
                        .WithMany()
                        .HasForeignKey("PreferredPrinterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DigitalTwin.Domain.Entities.PrinterTask", "StartedPrinterTask")
                        .WithMany()
                        .HasForeignKey("StartedPrinterTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedPrinter");

                    b.Navigation("PreferredPrinter");

                    b.Navigation("StartedPrinterTask");
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.Printer", b =>
                {
                    b.Navigation("AmsUnits");

                    b.Navigation("FirmwareStatus");

                    b.Navigation("SimulationControl");
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.PrinterTask", b =>
                {
                    b.Navigation("AmsDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
