// <auto-generated />
using System;
using DigitalTwin.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DigitalTwin.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DigitalTwinDbContext))]
    partial class DigitalTwinDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DigitalTwin.Domain.Entities.Printer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsAmsSupported")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastBindSyncAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal?>("NozzleDiameterMm")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("PrintStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Structure")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("printers", (string)null);
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.PrinterAmsSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NozzleTempMaxC")
                        .HasColumnType("integer");

                    b.Property<int?>("NozzleTempMinC")
                        .HasColumnType("integer");

                    b.Property<Guid>("PrinterAmsUnitId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RemainingLengthMm")
                        .HasColumnType("integer");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalLengthMm")
                        .HasColumnType("integer");

                    b.Property<string>("TrayColor")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TrayType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PrinterAmsUnitId", "SlotIndex")
                        .IsUnique();

                    b.ToTable("printer_ams_slots", (string)null);
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.PrinterAmsUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AmsDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("AmsIndex")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool?>("ForceUpdate")
                        .HasColumnType("boolean");

                    b.Property<int?>("HumidityLevel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LatestVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PrinterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReleaseStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("TemperatureCelsius")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId", "AmsIndex")
                        .IsUnique();

                    b.ToTable("printer_ams_units", (string)null);
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.PrinterFirmwareStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool?>("ForceUpdate")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastVersionSyncAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LatestVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PrinterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReleaseStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId")
                        .IsUnique();

                    b.ToTable("printer_firmware_statuses", (string)null);
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.PrinterAmsSlot", b =>
                {
                    b.HasOne("DigitalTwin.Domain.Entities.PrinterAmsUnit", "PrinterAmsUnit")
                        .WithMany("Slots")
                        .HasForeignKey("PrinterAmsUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrinterAmsUnit");
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.PrinterAmsUnit", b =>
                {
                    b.HasOne("DigitalTwin.Domain.Entities.Printer", "Printer")
                        .WithMany("AmsUnits")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.PrinterFirmwareStatus", b =>
                {
                    b.HasOne("DigitalTwin.Domain.Entities.Printer", "Printer")
                        .WithOne("FirmwareStatus")
                        .HasForeignKey("DigitalTwin.Domain.Entities.PrinterFirmwareStatus", "PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.Printer", b =>
                {
                    b.Navigation("AmsUnits");

                    b.Navigation("FirmwareStatus");
                });

            modelBuilder.Entity("DigitalTwin.Domain.Entities.PrinterAmsUnit", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
